version: "3.9"

services:
  regression:
    build: .
    container_name: ui-tests
    volumes:
      - .:/usr/workspace
      - ./allure-results:/usr/workspace/allure-results
    environment:
      LOGIN: ${LOGIN}
      PASSWORD: ${PASSWORD}
